package com.season.book.other;

<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE hibernate-configuration PUBLIC
          "-//Hibernate/Hibernate Configuration DTD 3.0//EN"
          "http://hibernate.sourceforge.net/hibernate-configuration-3.0.dtd">
<!-- Generated by MyEclipse Hibernate Tools.                   -->
<hibernate-configuration>

	<session-factory>
		<property name="dialect">
			org.hibernate.dialect.Oracle9Dialect
		</property>
		<property name="connection.url">
			jdbc:oracle:thin:@localhost:1521:orcl
		</property>
		<property name="connection.username">SYSTEM</property>
		<property name="connection.password">123456</property>
		<property name="connection.driver_class">
			oracle.jdbc.OracleDriver
		</property>
		<property name="show_sql">true</property>
		<property name="format_sql">true</property>
		<mapping resource="org/hibernate/model/mapping/User.hbm.xml" />